### ISSUE TITLE
Manually passed axis keywords are overridden

### ISSUE THREAD

**Issue by jkrumbiegel** [JuliaPlots/AlgebraOfGraphics.jl#195]
If I do `draw(aog, axis = (xticks = 1:10, yticks = 5:20))` the ticks do not change. I assume there is some logic inside AlgebraOfGraphics that overrides these things? The manually passed keywords should always get priority

**Comment by piever** [comment]
Yes, I agree. #204 fixes that by only replacing ticks if the value was `automatic`.

Axis labels are mildly trickier, because the default is `""` rather than `automatic`, and I find it slightly more principled to check that the user did not set the value from the `Axis` object rather than by checking the user `axis = ...` named tuple.

Could we maybe change default axis labels to `automatic` rather than `""` or is that complicated? This would have the added side benefit that recipes will be able to set the label only if the user did not specify it (when we allow recipes to manipulate the axis).

**Comment by jkrumbiegel** [comment]
Well, `automatic` doesn't mean default, it means that some sensible value is computed using other settings. For labels, that doesn't really make sense, as there are no other settings that would influence an automatically generated label.

**Comment by piever** [comment]
Ah, I see. The `axis` named tuple is passed to the `Axis` constructor directly, which I think is good, in case the user wants to pass in an observable. I guess I just need to do a small refactor so that when the labels and ticks are set by AoG I still have access to the named tuple of settings passed by the user.
