### ISSUE TITLE
weird marker/color cycling bug

### ISSUE THREAD

**Issue by ericphanson** [JuliaPlots/AlgebraOfGraphics.jl#197]
```julia
using AlgebraOfGraphics #v0.4.2
using CairoMakie # v0.5.4
mwe_data = (; t = 1:20, y1 = ones(20), y2 = rand(20))
mwe_names = ["f_n", "f_d"]
data(mwe_data) * mapping("t", ["y1", "y2"] .=> "y"; color = dims(1) => (i -> mwe_names[i]), marker=dims(1)) * (visual(Lines) + visual(Scatter)) |> draw
```
![7ed230be-15a5-4827-8fbb-3be45cd493f4](https://user-images.githubusercontent.com/5846501/120115682-232e9a80-c185-11eb-95a7-6b9f954a69e7.png)

What's wrong with this? Well, there is no orange circle or blue triangle! Also, if you change `mw_names = ["y1", "y2"]` then it's fixed. So I think something is getting alphabetized incorrectly, or something like that.

**Comment by piever** [comment]
The issue is that the transformation in the `mapping` syntax completely replaces the original data, so if you do different transformations to the same variable and use the result for different mappings (here `color` and `marker`), entries will be "mismatched".

#198 just throws an error if a variable with the same name have different unique values. This may require better automated naming of the `dims` context to be viable.

An alternative would be to have not as many legends as there are unique variable names, but if the same variable name corresponds to different unique value (as in your MWE), split as two legends. This latter approach may actually be helpful in contexts where there is no automated naming.

Do you have any intuition as to which would be more reasonable (throw error or split legends if the same variable names correspond to different sets of unique entries)?

**Comment by ericphanson** [comment]
Hm, not sure I fully understand, but let me give the context— this was reduced from an example where I had 15 series to plot, and with the color cycling, I couldn’t distinguish all of them. So I wanted to also add marks in order to have more combinations of things (so maybe I can’t distinguish two blue lines, but I can blue circles from blue triangles). Is there another way to do that?

**Comment by piever** [comment]
I think the problem is that you need to apply the relabeling to _both_ marker and color. For example

```julia
julia> d = Dict(:x => 1:10, (y => rand(10) for y in ys)...);

julia> group = dims(1) => (c -> ys[c]) => "category";

julia> plt = data(d) * mapping(:x, ys .=> "y", color=group, marker=group) * (visual(Lines) + visual(Scatter));

julia> draw(plt)
```

![cycle](https://user-images.githubusercontent.com/6333339/120190305-b533b300-c218-11eb-99f2-5683a275e963.png)

With #198, if you only rename one of them, it will now give an error rather than creating the wrong legend.

There is a separate issue that renaming things can change the order (it will default to the order of what is returned by the renaming transformation, in this case lexicographic ordering of strings). I'll add a simple way to rename `dims` while preserving the order.

**Comment by ericphanson** [comment]
Ohh ok, that makes sense. I thought the renaming was only needed for color but I’m not sure why 😅. I guess because it seemed to work in some cases, so the error will be very helpful.

**Comment by ericphanson** [comment]
Thanks for the fixes! Would you mind tagging a release?

**Comment by piever** [comment]
Sure! https://github.com/JuliaRegistries/General/pull/37887
