### ISSUE TITLE
StatsMakie redesign

### ISSUE THREAD

**Issue by piever** [JuliaPlots/AlgebraOfGraphics.jl#2]
This is an attempt to condensate the"grammar of graphics" like part of StatsMakie in a stand-alone, low-dependency package.

The current design is as follows. The basic building blocks are similar to the current building blocks of StatsMakie: `Analysis`, `Group`, `Select` (name to be decided), and `Data`. On top of them, they can be combined algebraically using `⊗` and `⊕` (if I'm sure this does not lead to piracy, `*` and `+` would also be an option).

This is the envisioned syntax.

```julia
spec = Data(mpg) ⊗ Select(:Displ, :Hwy)
scatter(spec)
```
![scatter](https://user-images.githubusercontent.com/6333339/76550846-ada8b280-648a-11ea-9920-42f8505bedb9.png)

```julia
scatter(spec ⊗ Group(Marker = :Cyl, color = :Year))
# maybe also
scatter(spec, Group(Marker = :Cyl, color = :Year))
```

![scatter_group1](https://user-images.githubusercontent.com/6333339/76550872-b9947480-648a-11ea-8e64-a5e2ab4278df.png)

```julia
plot((Scatter ⊕ linear) ⊗ spec ⊗ Group(color = :Cyl))
# maybe also
plot(Scatter ⊕ linear, spec, Group(color = :Cyl))
```

![scatter_analysis](https://user-images.githubusercontent.com/6333339/76550970-de88e780-648a-11ea-9880-3ca276917b7a.png)

The main technical decisions IMO are the following.

In this proof of concept, `Select` encompasses both positional and keyword arguments (i.e. `Select(col1, col2, markersize = col3)`), and `Analysis` takes a `Select` and returns a `Select`. This simplifies things a bit but now `scatter(Data(mpg), :Hwy, :Displ)` needs to be `scatter(Data(mpg), Select(:Hwy, :Displ))`. Maybe one can assume that all the non-group arguments after the data are part of `Select`. At the other end of the spectrum, one could avoid `Select` altogether with `NamedTuples` as we do [here](https://github.com/JuliaPlots/StatsMakie.jl/blob/master/test/runtests.jl#L111) for example.

There is a function `traces` that computes the traces. So far, in the most general case, it returns a list of `metadata => Vector{Trace}` objects. Each `metadata => Vector{Trace}` corresponds to a product in the expansion of the plot specification. For example `traces((Scatter ⊕ linear) ⊗ spec ⊗ Group(color = :Cyl))` would return `((Scatter,) => some_traces, (linear,) => some_other_traces)`, where the `some_traces` are one per value of `:Cyl`. Choosing exactly what this looks like is important because this is what the plotting package needs to be able to plot. Each `Trace` has some attributes (which come from the grouping), as well as a `Select` that gives the values of positional and keyword arguments that come from the overall `Select` (potentially transformed by an `Analysis`).

Final point is whether the  `⊗` and `⊕` syntax (or `+` and `*`) is actually better than maybe just multiple arguments and commas. The comparison would be between:

```julia
plot((Scatter ⊕ linear) ⊗ spec ⊗ Group(color = :Cyl)) # option 1
plot((Scatter + linear) * spec * Group(color = :Cyl)) # option 2
plot(Scatter ⊕ linear, spec, Group(color = :Cyl)) # option 3
plot(Scatter + linear, spec, Group(color = :Cyl)) # option 4
plot((Scatter, linear), spec, Group(color = :Cyl)) # option 5
```

I kind of like that one can use the "distributive law" in option 1 and 2 to understand what will happen.

I suspect this is not orthogonal to the previous discussion on `Select`, as using a "custom type" will probably allow to use a `Base` operator.

**Comment by piever** [comment]
A final point to be discussed is how the adoption of this approach would work. I suspect the easiest is that AbstractPlotting takes a dependency on AlgebraOfGraphics so that it can natively support `Group` and company (I think it already indirectly depends on AlgebraOfGraphics dependencies), and defines a recipe for `AbstractElement` (which should be the common abstract type, see https://github.com/piever/AlgebraOfGraphics.jl/pull/3).

**Comment by sethaxen** [comment]
Thanks for doing this! I'm still trying to wrap my head around GoG and how to cleanly split things but still have a simple intuitive syntax for plotting, and I have some questions about this approach.

I don't yet understand the "algebra of graphics" part. An algebra strictly speaking has addition and multiplication, where multiplication is distributive. Elements of an algebra can also be multiplied by scalars (without this property, it's a ring instead of an algebra).

What determines whether two elements can be added or multiplied? What would adding a `Lines` to a `Data` do?

> This simplifies things a bit but now `scatter(Data(mpg), :Hwy, :Displ)` needs to be `scatter(Data(mpg), :Hwy, :Displ)`.

These two are the same, yes?

In this envisioning, `Select` also absorbs the functionality of the old `Style`, right? One thing I found challenging with the old grammar was styling by a categorical variable. e.g. if I have `Select(:Hwy, :Displ, markersize = :Cyl)`, I'll get markers of different sizes with some default scale, but what if I want to scale them nontrivially based on `:Cyl`? Moreover, what if I wanted to group by some discretizing function of a continuous variable (e.g. `:(Hwy < 25)`)?

I still think that `Group` always splitting the data into individual traces will in the long run be limiting unless that can be customized. e.g. for stacked densities. When stacking densities, you'll want to first have a shared x-axis grid, then compute the densities individually, then shift the y-values, then plot.

**Comment by piever** [comment]
> I don't yet understand the "algebra of graphics" part. An algebra strictly speaking has addition and multiplication, where multiplication is distributive. Elements of an algebra can also be multiplied by scalars (without this property, it's a ring instead of an algebra).

Yes, I'm being a bit sloppy, technically it is a semiring (just `+` and `*`), but I confess I like the sound of "algebra of graphics" better :)

> What determines whether two elements can be added or multiplied? What would adding a `Lines` to a `Data` do?

The whole idea is that "adding" is just a trick to factor out the common part in two plots. Lets say for example that you have `cols = Data(mpg) * Select(:Hwy, :Displ)`. You want to do a non linear regression on the whole data (no splitting), then group by `:Cyl` and do a scatter with also the linear fit. These three plots (non-linear, linear, and scatter) share a lot of stuff that can be factored together:

```julia
cols = Data(mpg) * Select(:Hwy, :Displ)
spec = (smooth + (Scatter + linear) * Group(:Cyl)) * cols
plot(spec)
```

So the addition just exists "formally", with the idea that you will "expand" the whole thing into a sum of products, and plot all the addends on top of each other. The product "combines" all of its factors in interesting ways. For example, while `(Scatter + linear) * cols` does two separate plots (scatter and linear regression), `Scatter * linear * cols` would replace the default geometry of `linear` (e.g. `Lines`) with `Scatter`.

>> This simplifies things a bit but now `scatter(Data(mpg), :Hwy, :Displ)` needs to be `scatter(Data(mpg), :Hwy, :Displ)`.
>
> These two are the same, yes?

Ups, the second was supposed to be `scatter(Data(mpg), Select(:Hwy, :Displ))`, I've edited above.

> In this envisioning, `Select` also absorbs the functionality of the old `Style`, right?

Yes, that's the idea.

> One thing I found challenging with the old grammar was styling by a categorical variable. e.g. if I have `Select(:Hwy, :Displ, markersize = :Cyl)`, I'll get markers of different sizes with some default scale, but what if I want to scale them nontrivially based on `:Cyl`? Moreover, what if I wanted to group by some discretizing function of a continuous variable (e.g. `:(Hwy < 25)`)?

At the moment you'd need to add a new column to the data, but I can imagining supporting things like `DataFrames.select` (not yet implemented there either I think), where you could do `Group(color = :Hwy => <(25))`, passing a `Symbol => Function` pair. "Scales" are not yet supported, but somehow I wonder whether they should come from AbstractPlotting. For example, if you want the marker size to vary with the logarithm of the variable, this IMO is an AbstractPlotting feature. `Select(markersize = :Cyl => log)` would be slightly different, in that I imagine you would get a legend for the variable `log(Cyl)`. This definitely requires a bit more thought.

> I still think that `Group` always splitting the data into individual traces will in the long run be limiting unless that can be customized. e.g. for stacked densities. When stacking densities, you'll want to first have a shared x-axis grid, then compute the densities individually, then shift the y-values, then plot.

I think this is an artifact of the current implementation of `MultiplePlots`. Somehow I believe there should be a fallback `plot!(plt::PlotType, vector_of_traces)`, which is just plot all the series on top of each other calling `plot!(plt, single_trace)` repeatedly, but it should be possible to overload for say `plot!(plt::DotPlot, vector_of_traces)` to change that behavior. I completely agree than the various plot types need to have access to the whole data if they need it.

**Comment by Tokazama** [comment]
Here are my first impressions while I'm thinking upon this. I really like that you've continued with the non-macro approach. We can always add that later if it seems necessary, but this give a nice place to optimize everything first. 

I'm pretty against using unicode like ` ⊗ ` as the primary option anything. If we do use it I think it should be an alias for another command (e.g., `multiply`). It's just one of those things that makes it hard for people completely new to Julia to pick this up. They suddenly have no idea how to even type the commands in their favorite text editor.

I really like the idea of moving away from a bunch of commas and the list of 100 keyword arguments in the `plot` method. However, syntax is valuable and if we use it here we may not be able to use it for something in a different part of plotting. Maybe we should see if theirs a more general use in the plotting ecosystem that people want these for before claiming them. 

I'll add to the options a bit more just to generate some more ideas, not necessarily because I have a strong preference for anything yet. We could use `Group` as a composed function (option 6).
* Pros: This is nice like the operator syntax because it still makes it clear that `spec` and the contents of `Group` are interacting in some way (as opposed to just using a comma). It also seems a bit clearer to me that `Group` is operating on `spec` to change the view into it for the `plot` method` (e.g., assuming it produces some sort of new data type like `GroupData`).
* Cons: Unless we have a very strict composition for `Group` (no fields with abstract types) then it creates another step where performance will be abysmal. Also, it's debatably not be as pretty as using operators.

```julia
plot((Scatter ⊕ linear) ⊗ spec ⊗ Group(color = :Cyl)) # option 1
plot((Scatter + linear) * spec * Group(color = :Cyl)) # option 2
plot(Scatter ⊕ linear, spec, Group(color = :Cyl)) # option 3
plot(Scatter + linear, spec, Group(color = :Cyl)) # option 4
plot((Scatter, linear), spec, Group(color = :Cyl)) # option 5
plot((Scatter, linear), Group(color = :Cyl)(spec)) # option 6
```

**Comment by piever** [comment]
In the end I'm convincing myself that `+` and `*` is the best API. These composable components are quite nice and one can keep mixing and matching to create different plots.

The intuition (in terms of classical GoG) is the following. A "product of atomic components" corresponds to a layer in the GoG sense (geometry, transformation, aesthetics, and also position info once we implement it). So our `*` is ggplot2 `+` _for a single layer_.

Our `+`, on other hand, implements multiple layers (each addend being one), with the added benefit that, using distributivity, we can factor together common parts. For example, once we have a given plot, say `plotspec  = Scatter * Select(:Col1, :Col2) * Group(marker = :Col3)`, we can apply to two different datasets as follows:

```julia
dfs = Data(df1) + Data(df2)
plot(dfs * plotspec)
```

I suspect here we may also want to add a container for keyword arguments in the plot (say recycle the old `Style`), so that the different layers can have their own private attributes, for example

```julia
dfs = Data(df1) * Style(color = colorant"red") + Data(df2) * Style(color = colorant"blue")
plot(dfs * plotspec)
```


> I really like the idea of moving away from a bunch of commas and the list of 100 keyword arguments in the `plot` method. However, syntax is valuable and if we use it here we may not be able to use it for something in a different part of plotting. Maybe we should see if theirs a more general use in the plotting ecosystem that people want these for before claiming them.

Yes, this definitely needs to be discussed. We are not really "claiming" them, as we are just adding overloads for types we own on `Base` operations, but I agree that, for this to be useful, `AbstractPlotting` should "consent" to implement `+` and `*` on `PlotType`.
