### ISSUE TITLE
Plotting to `FigurePosition`s of a `FigureGrid`

### ISSUE THREAD

**Issue by MichaelHatherly** [JuliaPlots/AlgebraOfGraphics.jl#219]
Since the `FigureGrid` contains a `Makie.Figure` I assumed that it would be possible to add extra axes for some normal `Makie` plots to a `FigureGrid` in the following way by just using `fg.figure[1, 2]`:

```
julia> using AlgebraOfGraphics, CairoMakie
       set_aog_theme!();

       axis = (width = 225, height = 225);
       penguin_frequency = data(penguins) * frequency() * mapping(:species);

       fg = draw(penguin_frequency; axis)
Scene (314px, 307px):
  18 Plots:
...
  1 Child Scene:
    └ Scene (225px, 225px)

julia> scatter(fg.figure[1, 2], 1:5, rand(5))
Makie.AxisPlot(Axis (1 plots), Scatter{Tuple{Vector{Point{2, Float32}}}})

julia> fg
Scene (314px, 307px):
  36 Plots:
...
  2 Child Scenes:
    ├ Scene (225px, 225px)
    └ Scene (1px, 225px)
```

It _nearly_ works, but the second axis doesn't get correctly sized. Is this something that can be supported?

**Comment by piever** [comment]
Ah, I think the problem is that AlgebraOfGraphics resizes the figure to match the content, if all the contents have explicit sizes, see [this line](https://github.com/JuliaPlots/AlgebraOfGraphics.jl/blob/18535745c30e5bc8890182056c7bd5eef8c32d1a/src/algebra/layers.jl#L153).

I think you can either avoid giving explicit dimensions to the axis, so that it does not try resizing, eg `fg = draw(penguin_frequency)`, or maybe give explicit dimensions to both and resize again at the end, eg, after your code

```
scatter(fg.figure[1, 2], 1:5, rand(5); axis)
AlgebraOfGraphics.resizetocontent!(fg)
```

**Comment by MichaelHatherly** [comment]
That makes sense, and works fine, thanks. Would it be worth adding something about this to the FAQ? Additionally, is `.figure` of the `FigureGrid` regarded as part of the package's public interface and something we can rely on for combining plots like this?

**Comment by piever** [comment]
A doc PR for that would be great!

I think the result of `draw` should always have a figure object that is accessible, though it may be better to add a `Figure(fg::FigureGrid)` method to extract it as official API.

**Comment by MichaelHatherly** [comment]
I'll put something together later today then.
