### ISSUE TITLE
`titlevisible` ignored in legend customization

### ISSUE THREAD

**Issue by icweaver** [JuliaPlots/AlgebraOfGraphics.jl#309]
Following up from slack, `titlevisible` seems to be ignored when trying the legend tweaking capabilities introduced in #291

```julia
using AlgebraOfGraphics, CairoMakie

N = 30

df = DataFrame(
	Fruit = rand(["apple", "pear", "banana", "watermelon"], N),
	Country = rand(["US", "CA", "MX"], N),
	Weight = rand(1:10, N),
)

plt = data(df) *
    mapping(:Fruit, :Weight, dodge=:Country, color=:Country) *
	visual(BarPlot)

draw(plt, legend=(position=:top, titlevisible=false))
```

![index](https://user-images.githubusercontent.com/25312320/144681465-5323463c-afc6-4235-a2e8-5acd0d1c9352.png)

**Comment by piever** [comment]
Related issue (cross-posting from [discourse](https://discourse.julialang.org/t/algebraofgraphics-question/72982/4)), which is probably solvable directly in AoG is to call the correct "title-free" MakieLayout `Legend` method when there are no titles to get the correct layout (without additional empty space).

**Comment by piever** [comment]
So, the syntax `color = :Country => ""` now removes "most" of the extra space associated to the title, even though a little bit remains. I suspect it is a small issue with MakieLayout correctly removing the title space but not the padding between title and entries. It could probably be easier to fix it there, so that AlgebraOfGraphics can always call the same method.

**Comment by icweaver** [comment]
Oh wow, thanks for remembering this, haha. I see what you mean, happy to close this here in favor of a future upstream fix. Thanks for pointing me in the right direction and for all of your work on this!
