### ISSUE TITLE
Invisible boxes when creating boxplot with Dates axis

### ISSUE THREAD

**Issue by non-Jedi** [JuliaPlots/AlgebraOfGraphics.jl#369]
## Bug description

When the x-axis values of a boxplot are of type `Dates.Date`, the boxes are invisible when plotting `visual(BoxPlot)`. This very well may be an upstream issue, but you'll have to direct me to the proper repo to file against if so and how to reproduce using the lower-level package.

## Steps to reproduce

```julia
using Dates, DataFrames, AlgebraOfGraphics, CairoMakie
dftest = DataFrame(a = rand(Date(2022, 1):Day(1):Date(2022,2), 2000), b = rand(2000))
save("dates-boxplot-aog.png", draw(data(dftest) * mapping(:a, :b) * visual(BoxPlot)))
```

## Images

![dates-boxplot-aog](https://user-images.githubusercontent.com/17915621/157769999-16b870e0-9674-4eef-8af5-d0de43742184.png)

## Version info

```
Julia Version 1.7.2
Commit bf53498635 (2022-02-06 15:21 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-10810U CPU @ 1.10GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, skylake)
```

```
  [cbdf2221] AlgebraOfGraphics v0.6.5
  [13f3f980] CairoMakie v0.7.4
  [a93c6f00] DataFrames v1.3.2
  [ade2ca70] Dates
```

**Comment by piever** [comment]
Thanks for the nice report!

I actually think this is a "shared responsibility bug". From what I understand, `Makie.boxplot` defaults to `width=1` for the boxes, which IMO is reasonable, but interacts very badly with the date conversion (where the unit used is the millisecond). So, in your plot the boxes exist but have width `1ms` (essentially, invisible). You could try
```julia
draw(data(dftest) * mapping(:a, :b) * visual(BoxPlot, width=86_400_000)) # number of milliseconds in a day
```
to get a reasonably looking plot.

A similar issue can be reproduced in Makie with `boxplot(rand(1:3, 100) .* 10^6, rand(100))`.

One could (either in AoG or directly in Makie) get `boxplot`'s bar width to default to the minimum distance between distinct `x` values, but I don't really like that solution (it's a bit brittle in case some data is missing from some subplots or subtraces, or if there is only one entry). Maybe a better solution is to use `oneunit(T)` instead of `1` as default width for `boxplot`, `barplot` and `violin` (so default to one day for dates).
