### ISSUE TITLE
How to pass multiple pre-grouped vectors?

### ISSUE THREAD

**Issue by jkrumbiegel** [JuliaPlots/AlgebraOfGraphics.jl#79]
I have a data transformation pipeline that returns a vector of vectors with floats, and a vector of strings, which name the groups. This doesn't work:

```julia
vecs = [randn(100) for _ in 1:10]
names = string.(1:10)

data((vecs = vecs, names = names)) * ...
```

But concatenating all the vectors into one works. This seems an unnecessary step as it forces me to create a long-format table. Is there a better way?

**Comment by piever** [comment]
Yes, you don't need to go back to long format (even though naming supported is wip for pregrouped vectors).

The trick is to use the `dims()` context (i.e., every entry of the array is a trace).

For example:

```julia
vecs = [randn(100) for _ in 1:10]
dims() * style(vecs, color=dims(1))
```

does what you want. One could have gotten here from [this example](http://juliaplots.org/AlgebraOfGraphics.jl/dev/generated/tutorial/#Non-tabular-style-(slicing-context)-1), but I guess it's better to add an explicit example here. Automatic naming in this scenario is not supported (#64), but should just be a matter of picking an array with named indices. As usual in julia, there's a bunch of packages that do that (I already use NamedDims for named _dimensions_, so maybe something that builds on that would be nice).

I suspect that `dims()` could become the default context to be honest, so that just

```julia
vecs = [randn(100) for _ in 1:10]
style(vecs, color=dims(1))
```

works. I need to think whether there are some drawbacks to this (it also depends how common this scenario is).
