### ISSUE TITLE
Customizing aspects other than plot attributes

### ISSUE THREAD

**Issue by jkrumbiegel** [JuliaPlots/AlgebraOfGraphics.jl#85]
There are settings that don't relate to specific plot objects (which can be passed in `spec` calls). Examples are column and row gaps in facet layouts, the color and style of the facet labels. The facets appear because `style(layout_x = :some_variable)` is used, so where would be a good place to customize this behavior and pass additional kwargs?

Another example that comes to mind is renaming legend titles, entries, x/ylabels etc. GGplot uses some extra functions for that which you add to the whole command chain, I think.

I was wondering if you thought about this already, as so far some things seem to be hard-coded for simplicity.

**Comment by jkrumbiegel** [comment]
one more attribute that I currently have to set manually after the fact is whether all axes are x/y linked or only those within rows / columns. This is currently hardcoded to only rows/columns, and we should come up with a good way to set these parameters

**Comment by jtrakk** [comment]
I'd like to set a title this way too, like ggtitle().

**Comment by VPetukhov** [comment]
Yes, having something for setting x/y labels, title, etc would be very helpful!

**Comment by piever** [comment]
I'm working on a rewrite of AlgebraOfGraphics, as I still really like the idea of combining basic building blocks with `+` and `*`, but I think the current implementation is a bit problematic / inflexible in terms of plot customization.

Current WIP status is [here](https://piever.github.io/SplitApplyPlot.jl/dev). In particular, I was thinking along the lines of `color = :Cyl => categoricalscale => "Cylinders"` to pass labels and scales. The scale would in turn also encode the "linking" information.

I'm still a bit confused as to how this would work when the analysis returns novel variables (say a `density` plot). I should probably distinguish the notion of `scale` and `label` pre or post analysis, but it's not yet completely clear in my mind.

For more sophisticated tweakings, I would actually prefer to return a sensible object where the tweaking can happen, see https://piever.github.io/SplitApplyPlot.jl/dev/generated/entries/.

**Comment by VPetukhov** [comment]
Thanks for doing this, @piever ! The syntax `color = :Cyl => categoricalscale => "Cylinders"` is really nice for quick customization! Do you think it can be extended for full-scale option tuning? From my experience with ggplot, when one starts tuning plots for scientific publications, such styling can get quite lengthy. And in their case, having [scales, guides](https://ggplot2-book.org/scales-guides.html) and [themes](https://ggplot2-book.org/polishing.html) kinda nails it down. Though, distinction between the three is often vague, which can be quite confusing. And another nice feature of having each scale as an object is that a user can create one scale and add it to a bunch of related plots.
I didn't really think on a perfect implementation, but maybe instead of having the second pair it would be better to create an object? Like `color = :Cyl => CategoricalScale("Cylinders", palette=:RdYlBu)` or `color = :Cyl => Scale(:categorical, "Cylinders", palette=:RdYlBu)`? Then, it also should be easy to implement adding such objects:
```julia
sc = Scale(transform=:log10, expand=(0, 1), grid=false)
entries(
    ...,
    x = :V1 => ContinuousScale("x axis") + sc,
    y = :V2 => ContinuousScale("y axis") + sc,
    ...
)
```

**Comment by jtrakk** [comment]
It seems like there are a bunch of options. e.g. `Color(:Cyl) * CategoricalScale() * Name("Cylinders")` Maybe it's worth listing them and identifying their tradeoffs.
